services:
  postgres:
    image: postgres
    container_name: postgresgrafana
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grafanadb

  adminer:
    image: adminer
    container_name: adminergrafana
    restart: always
    ports:
      - 8080:8080

  #zipkin
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9540:9411'

  #prometheus
  prometheus:
    image: prom/prometheus
    container_name: my-promethes-observability
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  #tempo
  my-tempo:
    image: grafana/tempo
    container_name: my-tempo-observability
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "4200:3200"
      - "9511:9411"

  #loki
  my-loki:
    image: grafana/loki:main
    container_name: my-loki-observability
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "4100:3100"

  #grafana
  my-grafana:
    image: grafana/grafana
    container_name: my-grafana-observability
    restart: unless-stopped
    ports:
      - "4000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./docker/grafana/:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_USER=root
      - GF_SECURITY_ADMIN_PASSWORD=root